name: Daily Report

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Cache Rust Builds
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build -r

      - name: Modify Config File
        run: |
          sed 's/1145141919/2020300834/' at_school.example.toml > config.toml
          sed -i 's/998244353/${{ secrets.PASSWORD }}/' config.toml
          sed -i 's/田所/刘子骞/' config.toml

      - name: Report
        run: ./target/release/syq -r
